// webapp/src/app/app.component.ts
import { Component } from '@angular/core';

import { MaterializeAction, MaterializeModule } from 'angular2-materialize';

import 'hammerjs';
import 'materialize-css';
import * as $ from 'jquery';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: string;

  constructor() {
    this.title = 'Alimentação Escolar - SME';
  }

  ngOnInit() {
  }
}

<!-- Navbar goes here -->
<nav id="rm" class="nav-default-color">
    <div class="nav-wrapper">
        <a routerLink="/" class="brand-logo">{{ title }}</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
            <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
            <li routerLinkActive="active">
                <a md-line routerLink="/">Home</a>
            </li>
            <li routerLinkActive="active">
                <a md-line routerLink="/about">Sobre</a>
            </li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
            <li routerLinkActive="active">
                <a md-line routerLink="/">Home</a>
            </li>
            <li routerLinkActive="active">
                <a md-line routerLink="/about">Sobre</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Page Layout here -->
<div class="row">
    <div class="col s12 m4 l3"> <!-- Note that "m4 l3" was added -->
        <!-- Grey navigation panel
            This content will be:
            3-columns-wide on large screens,
            4-columns-wide on medium screens,
            12-columns-wide on small screens
        -->
    </div>

    <div class="col s12 m8 l9"> <!-- Note that "m8 l9" was added -->
        <!-- Teal page content
            This content will be:
            9-columns-wide on large screens,
            8-columns-wide on medium screens,
            12-columns-wide on small screens
        -->

        <div class="">
            <router-outlet></router-outlet>
        </div>
    </div>
</div>

// webpack_vuejs/client/src/js/App.vue
<template>
  <div>
    <nav>
      <div class="nav-wrapper">
        <router-link class="brand-logo" to="/">{{ title }}</router-link>
        <!-- <a href="#!" >Logo</a> -->
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><router-link to="/map">Map</router-link></li>
          <li><router-link to="/about">About</router-link></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><router-link to="/map">Map</router-link></li>
          <li><router-link to="/about">About</router-link></li>
        </ul>
      </div>
    </nav>

    <router-view></router-view>
  </div>
</template>

<script scoped>
  export default {
    name: 'app',
    data() {
      return {
        title: 'Alimentação Escolar - SME'
      },
      created() {
        $(document).ready(function(){
          $(".button-collapse").sideNav();
        })
      }
    }
  }
</script>

<style>
</style>
